import { Router } from '@angular/router';
import { BehaviorSubject } from 'rxjs';
import { Component, OnInit, OnDestroy } from '@angular/core';
import { GlobalService } from 'src/app/services/global.service';

@Component({
  selector: 'app-layout',
  templateUrl: 'layout.component.html',
  styleUrls: ['layout.component.scss'],
})

export class LayoutComponent implements OnInit, OnDestroy{
  constructor(private _globalService: GlobalService, private router:Router) {}

  public verifyToken:any;
  public menuState:boolean = false;
  public menu = new BehaviorSubject<any[]>([]);
  public identity:any = localStorage.getItem('identity');
  public user = JSON.parse(this.identity);
  
  ngOnInit(){
    let token = localStorage.getItem('token');

    //Consultar permisos del usuario
    this._globalService.postRequest(`menuxUsuario`, {})
    .then((res:any)=>{this.menu.next(res.data)})
    .catch(()=>{this.router.navigate(['login']) })

    //Verificar token cada 30 segundos
    this.verifyToken = setInterval(()=>{
      this._globalService.getRequestToken(`validaToken?id=${this.user.id}&token=${token}`)
      .then((res:any)=>{ if(Number(res.data) != 1) this.router.navigate(['login']) })
      .catch(()=>{this.router.navigate(['login']) })
    }, 30000);

    //DATA MONITOREO EN LíNEA
    localStorage.setItem('data', JSON.stringify([
      {
          "ide_sitioventa": "100004",
          "fecha_creacion": "2018-12-06 00:00:00",
          "nom_sitioventa": "PDV Plaza De Toros",
          "nom_oficina": "Barrio Colombia",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 09:01:48",
          "fecha_primera_tx": "2023-02-20 09:26:54",
          "fecha_ultima_tx": "2023-02-20 18:06:08",
          "total_venta": 34600,
          "total_venta_chance": 32600,
          "total_venta_doble": 2000,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "1",
          "nom_tipositioventa": "Punto Venta"
      },
      {
          "ide_sitioventa": "108010",
          "fecha_creacion": "2018-01-01 00:00:00",
          "nom_sitioventa": "Granero El Paisa",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": "2023-02-20 07:05:56",
          "fecha_primera_tx": "2023-02-20 08:08:48",
          "fecha_ultima_tx": "2023-02-20 19:46:23",
          "total_venta": 96900,
          "total_venta_chance": 37900,
          "total_venta_doble": 59000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "1",
          "nom_tipositioventa": "Punto Venta"
      },
      {
          "ide_sitioventa": "100006",
          "fecha_creacion": "2021-03-02 00:00:00",
          "nom_sitioventa": "Pv Primero De Mayo",
          "nom_oficina": "Barrio Colombia",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 10:17:47",
          "fecha_primera_tx": "2023-02-20 10:28:27",
          "fecha_ultima_tx": "2023-02-20 20:43:00",
          "total_venta": 114900,
          "total_venta_chance": 92900,
          "total_venta_doble": 22000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "1",
          "nom_tipositioventa": "Punto Venta"
      },
      {
          "ide_sitioventa": "167011",
          "fecha_creacion": "2022-11-26 00:00:00",
          "nom_sitioventa": "Acertemos La Floresta",
          "nom_oficina": "Portal De Las Ferias",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 09:31:29",
          "fecha_primera_tx": "2023-02-20 10:05:48",
          "fecha_ultima_tx": "2023-02-20 18:10:23",
          "total_venta": 13400,
          "total_venta_chance": 11400,
          "total_venta_doble": 2000,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "1",
          "nom_tipositioventa": "Punto Venta"
      },
      {
          "ide_sitioventa": "167007",
          "fecha_creacion": "2020-12-03 00:00:00",
          "nom_sitioventa": "Pv Acertemos Los Sauces",
          "nom_oficina": "Portal De Las Ferias",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 09:03:59",
          "fecha_primera_tx": "2023-02-20 09:22:24",
          "fecha_ultima_tx": "2023-02-20 19:46:20",
          "total_venta": 52200,
          "total_venta_chance": 43200,
          "total_venta_doble": 9000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "1",
          "nom_tipositioventa": "Punto Venta"
      },
      {
          "ide_sitioventa": "108012",
          "fecha_creacion": "2020-02-05 00:00:00",
          "nom_sitioventa": "Acertemos Honda",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": "2023-02-20 07:06:24",
          "fecha_primera_tx": "2023-02-20 07:34:46",
          "fecha_ultima_tx": "2023-02-20 19:55:32",
          "total_venta": 198100,
          "total_venta_chance": 105100,
          "total_venta_doble": 93000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "1",
          "nom_tipositioventa": "Punto Venta"
      },
      {
          "ide_sitioventa": "108014",
          "fecha_creacion": "2020-10-06 00:00:00",
          "nom_sitioventa": "Acertemos Parque Timbio",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": "2023-02-20 06:56:39",
          "fecha_primera_tx": "2023-02-20 07:15:43",
          "fecha_ultima_tx": "2023-02-20 20:21:06",
          "total_venta": 147500,
          "total_venta_chance": 110500,
          "total_venta_doble": 37000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "1",
          "nom_tipositioventa": "Punto Venta"
      },
      {
          "ide_sitioventa": "138907",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Teresa Muñoz Muñoz",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 20:41:38",
          "fecha_primera_tx": "2023-02-20 09:26:05",
          "fecha_ultima_tx": "2023-02-20 20:31:48",
          "total_venta": 44800,
          "total_venta_chance": 35800,
          "total_venta_doble": 9000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "141901",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Nancy Fabiola Ordoñez Muñoz",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 08:32:46",
          "fecha_primera_tx": "2023-02-20 17:28:16",
          "fecha_ultima_tx": "2023-02-20 20:46:54",
          "total_venta": 53400,
          "total_venta_chance": 53400,
          "total_venta_doble": 0,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138904",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Sara Cecilia Collazos Galindez",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 17:57:56",
          "fecha_primera_tx": "2023-02-20 19:36:57",
          "fecha_ultima_tx": "2023-02-20 21:15:33",
          "total_venta": 31900,
          "total_venta_chance": 29900,
          "total_venta_doble": 2000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "108900",
          "fecha_creacion": "2020-10-27 00:00:00",
          "nom_sitioventa": "Movil Jesus Fernando Ordoñez",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": null,
          "fecha_primera_tx": "2023-02-20 09:36:01",
          "fecha_ultima_tx": "2023-02-20 19:30:25",
          "total_venta": 90300,
          "total_venta_chance": 41300,
          "total_venta_doble": 49000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138902",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Alvaro Muñoz Chilito",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 08:59:14",
          "fecha_primera_tx": "2023-02-20 12:01:10",
          "fecha_ultima_tx": "2023-02-20 19:39:52",
          "total_venta": 28350,
          "total_venta_chance": 16350,
          "total_venta_doble": 12000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "108902",
          "fecha_creacion": "2020-10-27 00:00:00",
          "nom_sitioventa": "Movil Maria Margoth Criollo",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": "2023-02-20 06:31:07",
          "fecha_primera_tx": "2023-02-20 10:04:33",
          "fecha_ultima_tx": "2023-02-20 21:20:23",
          "total_venta": 101500,
          "total_venta_chance": 87500,
          "total_venta_doble": 14000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138908",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Eneria Bahos Narvaez",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": "2023-02-20 09:40:34",
          "fecha_ultima_tx": "2023-02-20 20:25:48",
          "total_venta": 64699,
          "total_venta_chance": 57700,
          "total_venta_doble": 6999,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138913",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Octavio Duque Lopez",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 06:43:46",
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "R",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "167901",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Graciela Alegria",
          "nom_oficina": "Portal De Las Ferias",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 07:22:29",
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "R",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "108904",
          "fecha_creacion": "2020-10-27 00:00:00",
          "nom_sitioventa": "Movil Jose Alberto Soscue Zambrano",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138900",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Arcesio Oime Jimenez",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 20:21:48",
          "fecha_primera_tx": "2023-02-20 08:41:08",
          "fecha_ultima_tx": "2023-02-20 13:15:44",
          "total_venta": 112250,
          "total_venta_chance": 106250,
          "total_venta_doble": 6000,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "141902",
          "fecha_creacion": "2021-04-27 00:00:00",
          "nom_sitioventa": "Movil Gerardo Alberto Erazo Tintinago",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 11:05:49",
          "fecha_primera_tx": "2023-02-20 11:07:18",
          "fecha_ultima_tx": "2023-02-20 20:09:04",
          "total_venta": 17600,
          "total_venta_chance": 13600,
          "total_venta_doble": 4000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138916",
          "fecha_creacion": "2021-04-27 00:00:00",
          "nom_sitioventa": "Movil Nasaria Anacona Ytaz",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 20:11:40",
          "fecha_primera_tx": "2023-02-20 20:12:40",
          "fecha_ultima_tx": "2023-02-20 20:50:11",
          "total_venta": 9400,
          "total_venta_chance": 7400,
          "total_venta_doble": 2000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138906",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Magdalena Paz Samboni",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 08:54:35",
          "fecha_primera_tx": "2023-02-20 12:21:38",
          "fecha_ultima_tx": "2023-02-20 19:38:04",
          "total_venta": 31550,
          "total_venta_chance": 31550,
          "total_venta_doble": 0,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138905",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Felina Garzon Hormiga",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 07:56:27",
          "fecha_primera_tx": "2023-02-20 08:02:47",
          "fecha_ultima_tx": "2023-02-20 20:04:58",
          "total_venta": 76450,
          "total_venta_chance": 69450,
          "total_venta_doble": 7000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "167900",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Carmen Ayda Gansasoy Meneses",
          "nom_oficina": "Portal De Las Ferias",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 20:18:03",
          "fecha_primera_tx": "2023-02-20 20:19:34",
          "fecha_ultima_tx": "2023-02-20 20:23:59",
          "total_venta": 9000,
          "total_venta_chance": 7000,
          "total_venta_doble": 2000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "141900",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Emigdio Chilito Anacona",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 17:28:49",
          "fecha_primera_tx": "2023-02-20 17:42:13",
          "fecha_ultima_tx": "2023-02-20 20:43:19",
          "total_venta": 84800,
          "total_venta_chance": 77800,
          "total_venta_doble": 7000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138914",
          "fecha_creacion": "2021-04-27 00:00:00",
          "nom_sitioventa": "Movil Maria Del Carmen Mapallo Avirama",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 19:37:36",
          "fecha_primera_tx": "2023-02-20 21:19:13",
          "fecha_ultima_tx": "2023-02-20 21:20:32",
          "total_venta": 5050,
          "total_venta_chance": 5050,
          "total_venta_doble": 0,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "100903",
          "fecha_creacion": "2020-10-26 00:00:00",
          "nom_sitioventa": "Movil Javier Nicolas Mosquera",
          "nom_oficina": "Barrio Colombia",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138911",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Maria Patricia Sanchez Piamba",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 11:50:13",
          "fecha_primera_tx": "2023-02-20 17:56:31",
          "fecha_ultima_tx": "2023-02-20 20:46:52",
          "total_venta": 61300,
          "total_venta_chance": 61300,
          "total_venta_doble": 0,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "100901",
          "fecha_creacion": "2020-10-26 00:00:00",
          "nom_sitioventa": "Movil Jose Aldemar Yarpaz Golondrino",
          "nom_oficina": "Barrio Colombia",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N5",
          "detalle_no_ventas": [
              {
                  "fecha_sql": "2023-02-01 00:00:00 - 2023-02-15 00:00:00",
                  "fecha_ultima_tx": "2023-02-10 00:00:00",
                  "can_dias_sin_ventas": "10"
              }
          ],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138909",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Maria Leonor Sanchez Piamba",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N5",
          "detalle_no_ventas": [
              {
                  "fecha_sql": "2023-02-01 00:00:00 - 2023-02-15 00:00:00",
                  "fecha_ultima_tx": "2023-02-14 00:00:00",
                  "can_dias_sin_ventas": "6"
              }
          ],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138903",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Oscar Banguero",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "100902",
          "fecha_creacion": "2020-10-26 00:00:00",
          "nom_sitioventa": "Movil Emiro Jaimepiamba Chicangana",
          "nom_oficina": "Barrio Colombia",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 12:14:44",
          "fecha_primera_tx": "2023-02-20 12:16:10",
          "fecha_ultima_tx": "2023-02-20 19:10:32",
          "total_venta": 18400,
          "total_venta_chance": 18400,
          "total_venta_doble": 0,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "108907",
          "fecha_creacion": "2020-10-27 00:00:00",
          "nom_sitioventa": "Movil Jose Noe Garcia Mosquera",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": null,
          "fecha_primera_tx": "2023-02-20 18:31:02",
          "fecha_ultima_tx": "2023-02-20 18:31:02",
          "total_venta": 4800,
          "total_venta_chance": 4800,
          "total_venta_doble": 0,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "100900",
          "fecha_creacion": "2020-10-26 00:00:00",
          "nom_sitioventa": "Movil Delio Uzuriaga",
          "nom_oficina": "Barrio Colombia",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 08:52:46",
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "R",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138910",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Doris Del Carmen Zambrano",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138917",
          "fecha_creacion": "2022-09-26 00:00:00",
          "nom_sitioventa": "Movil Yuli Andrea Urbano",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138915",
          "fecha_creacion": "2021-04-27 00:00:00",
          "nom_sitioventa": "Movil Dalia Amparo Otoya Samboni",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "138901",
          "fecha_creacion": "2020-10-19 00:00:00",
          "nom_sitioventa": "Movil Manases Alarcon Piamba",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": "2023-02-20 09:35:34",
          "fecha_ultima_tx": "2023-02-20 20:43:37",
          "total_venta": 16250,
          "total_venta_chance": 16250,
          "total_venta_doble": 0,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "5",
          "nom_tipositioventa": "Ambulante"
      },
      {
          "ide_sitioventa": "100001",
          "fecha_creacion": "2018-01-01 00:00:00",
          "nom_sitioventa": "Of Barrio Colombia",
          "nom_oficina": "Barrio Colombia",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 08:23:07",
          "fecha_primera_tx": "2023-02-20 09:55:23",
          "fecha_ultima_tx": "2023-02-20 21:41:48",
          "total_venta": 168350,
          "total_venta_chance": 119350,
          "total_venta_doble": 49000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "6",
          "nom_tipositioventa": "Oficina"
      },
      {
          "ide_sitioventa": "141001",
          "fecha_creacion": "2018-01-01 00:00:00",
          "nom_sitioventa": "Of Sindical",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 07:23:36",
          "fecha_primera_tx": "2023-02-20 08:05:53",
          "fecha_ultima_tx": "2023-02-20 20:23:28",
          "total_venta": 165950,
          "total_venta_chance": 123950,
          "total_venta_doble": 42000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "6",
          "nom_tipositioventa": "Oficina"
      },
      {
          "ide_sitioventa": "138001",
          "fecha_creacion": "2015-06-02 00:00:00",
          "nom_sitioventa": "Of Galeria La 13",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 09:07:06",
          "fecha_primera_tx": "2023-02-20 10:01:14",
          "fecha_ultima_tx": "2023-02-20 18:46:02",
          "total_venta": 144400,
          "total_venta_chance": 130400,
          "total_venta_doble": 14000,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "6",
          "nom_tipositioventa": "Oficina"
      },
      {
          "ide_sitioventa": "108001",
          "fecha_creacion": "2014-10-07 00:00:00",
          "nom_sitioventa": "Of Timbio",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": "2023-02-20 06:10:06",
          "fecha_primera_tx": "2023-02-20 07:46:57",
          "fecha_ultima_tx": "2023-02-20 19:39:52",
          "total_venta": 74050,
          "total_venta_chance": 40050,
          "total_venta_doble": 34000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "6",
          "nom_tipositioventa": "Oficina"
      },
      {
          "ide_sitioventa": "167001",
          "fecha_creacion": "2017-03-21 00:00:00",
          "nom_sitioventa": "Of Portal De Las Ferias",
          "nom_oficina": "Portal De Las Ferias",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 07:50:06",
          "fecha_primera_tx": "2023-02-20 08:04:13",
          "fecha_ultima_tx": "2023-02-20 19:50:29",
          "total_venta": 99150,
          "total_venta_chance": 87150,
          "total_venta_doble": 12000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "6",
          "nom_tipositioventa": "Oficina"
      },
      {
          "ide_sitioventa": "138009",
          "fecha_creacion": "2018-01-01 00:00:00",
          "nom_sitioventa": "Plaza La 13",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 06:25:03",
          "fecha_primera_tx": "2023-02-20 07:41:05",
          "fecha_ultima_tx": "2023-02-20 11:45:55",
          "total_venta": 219200,
          "total_venta_chance": 211200,
          "total_venta_doble": 8000,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "7",
          "nom_tipositioventa": "Cabina"
      },
      {
          "ide_sitioventa": "138013",
          "fecha_creacion": "2020-09-07 00:00:00",
          "nom_sitioventa": "TAT Acertemos Calicanto",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 21:44:36",
          "fecha_primera_tx": "2023-02-20 18:11:43",
          "fecha_ultima_tx": "2023-02-20 20:42:31",
          "total_venta": 14700,
          "total_venta_chance": 10700,
          "total_venta_doble": 4000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "167005",
          "fecha_creacion": "2019-04-06 00:00:00",
          "nom_sitioventa": "TAT Miscelanea El Garaje De Juanca",
          "nom_oficina": "Portal De Las Ferias",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 20:33:12",
          "fecha_primera_tx": "2023-02-20 11:42:32",
          "fecha_ultima_tx": "2023-02-20 20:24:32",
          "total_venta": 27100,
          "total_venta_chance": 16100,
          "total_venta_doble": 11000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "167006",
          "fecha_creacion": "2019-07-31 00:00:00",
          "nom_sitioventa": "TAT Variedades Dromarked",
          "nom_oficina": "Portal De Las Ferias",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "167003",
          "fecha_creacion": "2019-04-06 00:00:00",
          "nom_sitioventa": "TAT Tienda Alameda",
          "nom_oficina": "Portal De Las Ferias",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 10:05:17",
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 2000,
          "total_venta_chance": 0,
          "total_venta_doble": 2000,
          "estado": "R",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "119007",
          "fecha_creacion": "2019-07-31 00:00:00",
          "nom_sitioventa": "Paispamba Dulces y Detalles",
          "nom_oficina": "Sotara",
          "nom_zona": "Centro",
          "nom_ciudad": "Sotara",
          "hora_ingreso": "2023-02-20 07:34:43",
          "fecha_primera_tx": "2023-02-20 08:11:08",
          "fecha_ultima_tx": "2023-02-20 08:12:56",
          "total_venta": 6000,
          "total_venta_chance": 6000,
          "total_venta_doble": 0,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "119008",
          "fecha_creacion": "2022-02-05 00:00:00",
          "nom_sitioventa": "Rio Blanco Sotara",
          "nom_oficina": "Sotara",
          "nom_zona": "Centro",
          "nom_ciudad": "Sotara",
          "hora_ingreso": "2023-02-20 07:57:13",
          "fecha_primera_tx": "2023-02-20 10:36:19",
          "fecha_ultima_tx": "2023-02-20 18:46:48",
          "total_venta": 5000,
          "total_venta_chance": 5000,
          "total_venta_doble": 0,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "108017",
          "fecha_creacion": "2022-02-21 00:00:00",
          "nom_sitioventa": "TAT Jg Tienda",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": "2023-02-20 08:47:48",
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "R",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "141010",
          "fecha_creacion": "2022-06-24 00:00:00",
          "nom_sitioventa": "Baloto Sindical",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "NX",
          "detalle_no_ventas": [
              {
                  "fecha_sql": "2023-02-01 00:00:00 - 2023-02-15 00:00:00",
                  "fecha_ultima_tx": null,
                  "can_dias_sin_ventas": null
              }
          ],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "108019",
          "fecha_creacion": "2022-05-25 00:00:00",
          "nom_sitioventa": "TAT La Floresta",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": "2023-02-20 09:01:10",
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "R",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "141005",
          "fecha_creacion": "2019-04-06 00:00:00",
          "nom_sitioventa": "TAT Tienda Mary Luz",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 08:32:19",
          "fecha_primera_tx": "2023-02-20 17:12:20",
          "fecha_ultima_tx": "2023-02-20 19:38:22",
          "total_venta": 7000,
          "total_venta_chance": 7000,
          "total_venta_doble": 0,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "108022",
          "fecha_creacion": "2022-10-31 00:00:00",
          "nom_sitioventa": "TAT El Arado",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": "2023-02-20 10:21:47",
          "fecha_primera_tx": "2023-02-20 18:49:45",
          "fecha_ultima_tx": "2023-02-20 20:03:06",
          "total_venta": 7800,
          "total_venta_chance": 7800,
          "total_venta_doble": 0,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "141008",
          "fecha_creacion": "2022-02-18 00:00:00",
          "nom_sitioventa": "TAT San Jose De Los Tejares",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 08:11:33",
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "R",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "141009",
          "fecha_creacion": "2022-06-15 00:00:00",
          "nom_sitioventa": "Baloto Recuerdo",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "141011",
          "fecha_creacion": "2022-10-27 00:00:00",
          "nom_sitioventa": "TAT Tienda Karma",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "NX",
          "detalle_no_ventas": [
              {
                  "fecha_sql": "2023-02-01 00:00:00 - 2023-02-15 00:00:00",
                  "fecha_ultima_tx": null,
                  "can_dias_sin_ventas": null
              }
          ],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "141006",
          "fecha_creacion": "2019-04-08 00:00:00",
          "nom_sitioventa": "TAT Internet El Tunel",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 20:55:12",
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "R",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "167008",
          "fecha_creacion": "2021-06-22 00:00:00",
          "nom_sitioventa": "TAT Riveras De Occidente",
          "nom_oficina": "Portal De Las Ferias",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 15:46:03",
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "R",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "108023",
          "fecha_creacion": "2023-01-17 00:00:00",
          "nom_sitioventa": "TAT El Porton Cafe Bar",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "NX",
          "detalle_no_ventas": [
              {
                  "fecha_sql": "2023-02-01 00:00:00 - 2023-02-15 00:00:00",
                  "fecha_ultima_tx": null,
                  "can_dias_sin_ventas": null
              }
          ],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "167010",
          "fecha_creacion": "2022-04-08 00:00:00",
          "nom_sitioventa": "TAT Compu Isabela ",
          "nom_oficina": "Portal De Las Ferias",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "N5",
          "detalle_no_ventas": [
              {
                  "fecha_sql": "2023-02-01 00:00:00 - 2023-02-15 00:00:00",
                  "fecha_ultima_tx": "2023-02-13 00:00:00",
                  "can_dias_sin_ventas": "7"
              }
          ],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "138011",
          "fecha_creacion": "2019-04-06 00:00:00",
          "nom_sitioventa": "TAT Conexion Punto Net",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 11:19:05",
          "fecha_primera_tx": "2023-02-20 16:11:54",
          "fecha_ultima_tx": "2023-02-20 16:11:54",
          "total_venta": 3200,
          "total_venta_chance": 3200,
          "total_venta_doble": 0,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "141012",
          "fecha_creacion": "2022-12-19 00:00:00",
          "nom_sitioventa": "TAT Minimercado Sofia",
          "nom_oficina": "Sindical",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": null,
          "fecha_primera_tx": null,
          "fecha_ultima_tx": null,
          "total_venta": 0,
          "total_venta_chance": 0,
          "total_venta_doble": 0,
          "estado": "NX",
          "detalle_no_ventas": [
              {
                  "fecha_sql": "2023-02-01 00:00:00 - 2023-02-15 00:00:00",
                  "fecha_ultima_tx": null,
                  "can_dias_sin_ventas": null
              }
          ],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "100008",
          "fecha_creacion": "2022-04-05 00:00:00",
          "nom_sitioventa": "TAT Samuel",
          "nom_oficina": "Barrio Colombia",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 12:55:12",
          "fecha_primera_tx": "2023-02-20 18:23:47",
          "fecha_ultima_tx": "2023-02-20 18:24:27",
          "total_venta": 2000,
          "total_venta_chance": 2000,
          "total_venta_doble": 0,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "8",
          "nom_tipositioventa": "TAT (operadores)"
      },
      {
          "ide_sitioventa": "108002",
          "fecha_creacion": "2018-01-01 00:00:00",
          "nom_sitioventa": "Pv Timbio",
          "nom_oficina": "Timbio",
          "nom_zona": "Centro",
          "nom_ciudad": "Timbio",
          "hora_ingreso": "2023-02-20 07:11:36",
          "fecha_primera_tx": "2023-02-20 07:16:21",
          "fecha_ultima_tx": "2023-02-20 20:46:18",
          "total_venta": 138650,
          "total_venta_chance": 93650,
          "total_venta_doble": 45000,
          "estado": "V",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "9",
          "nom_tipositioventa": "Punto Oficina"
      },
      {
          "ide_sitioventa": "138002",
          "fecha_creacion": "2015-06-02 00:00:00",
          "nom_sitioventa": "Pv Galeria La 13",
          "nom_oficina": "Galeria La 13",
          "nom_zona": "Centro",
          "nom_ciudad": "Popayan",
          "hora_ingreso": "2023-02-20 09:11:24",
          "fecha_primera_tx": "2023-02-20 09:23:38",
          "fecha_ultima_tx": "2023-02-20 12:52:45",
          "total_venta": 100100,
          "total_venta_chance": 79100,
          "total_venta_doble": 21000,
          "estado": "A",
          "detalle_no_ventas": [],
          "tipo_sitioventa": "9",
          "nom_tipositioventa": "Punto Oficina"
      }
  ]))
  }

  ngOnDestroy(): void {
    clearInterval(this.verifyToken)
  }
}
